name: Bump kbcli on Chocolatey

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.5.1'
        required: true

jobs:
  chocolatey-bump:
    # needs: get-version
    name: Bump kbcli Chocolately
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Chocolately version
        run: choco --version
      - name: Install AU
        run: choco install au
      - name: Build Package
        working-directory: ./kbcli
        run: |
          ./update.ps1

      - name: Test Package Installer
        working-directory: ./kbcli
        run: Test-Package $Install
      - name: kbcli Version
        run: |
          refreshenv
          $env:Path += ";$env:TEMP\chocolatey\kbcli\$env:VERSION"
          kbcli version
      - name: Push Package to Chocolatey
        run: |
          Push-Package kbcli.
        working-directory: ./kbcli
        env:
          api_key: ${{ secrets.CHOCO_API_KEY }}
      - uses: EndBug/add-and-commit@v7
        with:
          message: "Bumping kbcli on Chocolatey ${{ github.event.inputs.version }}"
          add: "."
          cwd: "."